name: GNG Approval 

on:
  workflow_dispatch:
    # inputs: 
    #   gng:
    #     description: 'Go / No Go Id'
    #     required: true
jobs:
  gng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Test to see if Git Exists
        run: |
          git --help
          git remote -v
      - name: Test new branch commit
        run: | 
          touch mynewfile.txt
          echo $(date) > mynewfile.txt
          git checkout -b feat/new-branch
          git add mynewfile.txt
          git commit -m "Updated with new date"
          git push
      - name: Check GH CLI
        runs: | 
          gh --help
      # - name: GNG Approval with Puppeteer
      #   run: echo "node index.js --headless --gng=${{ inputs.gng }}"
      
