###############################################
#     Scope:
#       This Action is to show the
#       manipulation of the outputs from each job.
#
#     Problem Statement:
#       When using GITHUB ACTIONS Matrix it
#       was hard to persist some sort of data
#       to handle in the output/result of the run
#
#     Potential Caveats:
#       This may not work when the matrix steps
#       are run in parallel
################################################
name: Test

on:
  workflow_dispatch:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    outputs:
      "${{ matrix.words }}-test-output-result": ${{ steps.result-output.outputs.result }}
    strategy:
      matrix:
        words: ["hello", "bye", "sup"]

    steps:
      - name: Say Hello
        run: echo "Hello, World! ${{ matrix.words }}" >> results.txt
      - uses: actions/github-script@v7
        id: matrix-output
        with:
          script: |
            const fs = require('node:fs/promises');
            const data = await fs.readFile('results.txt')
            console.log(data)
      - run: echo "result=success" >> "$GITHUB_OUTPUT"
        id: result-output
  result-report:
    runs-on: ubuntu-latest
    needs: hello_world_job
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(${{ toJSON(needs) }})
