###############################################
#     Scope:
#       This Action is to show the
#       manipulation of the outputs from each job.
#
#     Problem Statement:
#       When using GITHUB ACTIONS Matrix it
#       was hard to persist some sort of data
#       to handle in the output/result of the run
#
#     Potential Caveats:
#       This may not work when the matrix steps
#       are run in parallel
################################################
name: Test

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - uses: actions/github-script@v7
        id: set-output-1
        with:
          script: |
            console.log('Setting output NAME=AZY')
            core.setOutput('name', 'Azy')
            console.log('------------------------')
            console.log("Printing out GITHUB_OUTPUT ENV Var")
            console.log(`GITHUB_OUTPUT: ${process.env.GITHUB_OUTPUT}`)
            console.log('------------------------')
            console.log("Trying to read GITHUB_OUTPUT")
            console.log(process.env.GITHUB_OUTPUT['name'])
            console.log("------------------------")
            console.log("Printing out all ENV vars")
            console.log(process.env)
      - name: "Read Output"
        run: |
          cat $GITHUB_TOKEN
