###############################################
#     Scope:
#       This Action is to show the
#       manipulation of the outputs from each job.
#
#     Problem Statement:
#       When using GITHUB ACTIONS Matrix it
#       was hard to persist some sort of data
#       to handle in the output/result of the run
#
#     Potential Caveats:
#       This may not work when the matrix steps
#       are run in parallel
################################################
name: Test

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - uses: actions/github-script@v7
        id: set-output-1
        with:
          script: return "Hello!"
          result-encoding: string
